# Backend CI/CD Pipeline
# Builds and tests the Node.js/TypeScript backend with mediasoup support

name: Backend CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # Job 1: Test
  test:
    name: Build and Test
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Setup Python for mediasoup native modules
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Verify build tools are installed on self-hosted runner
    # Setup instructions: See .github/RUNNER_SETUP.md
    - name: Verify build tools
      run: |
        echo "Node: $(node --version)"
        echo "NPM: $(npm --version)"
        python3 --version || python --version
        gcc --version || echo "GCC not found"
    
    # Start Redis for testing
    - name: Start Redis with Docker Compose
      run: |
        # Check if container exists
        if docker ps -a --format '{{.Names}}' | grep -q '^aladin-redis-prod$'; then
          echo "Container aladin-redis-prod already exists"
          
          # Check if it's running
          if docker ps --format '{{.Names}}' | grep -q '^aladin-redis-prod$'; then
            echo "✅ Redis is already running, reusing existing container"
          else
            echo "Starting stopped Redis container..."
            docker start aladin-redis-prod
            sleep 3
          fi
        else
          echo "Creating new Redis container with docker-compose..."
          docker-compose -f docker-compose.yml up -d redis
          sleep 5
        fi
        
        # Health check
        docker exec aladin-redis-prod redis-cli ping
        
        # Show status
        docker ps --filter name=aladin-redis-prod
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build TypeScript
      run: npm run build
    
    # - name: Run tests
    #   run: npm test
    
    - name: Check dist folder
      run: ls -la dist
    
    # Note: Redis container is kept running for next CI runs (faster startup)
  
  # Job 2: Deploy to Production (only on main branch push)
  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    needs: test
    if: |
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main' &&
      needs.test.result == 'success'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build TypeScript
      run: npm run build
    
    - name: Ensure Redis is Running (Production)
      run: |
        # Check if container exists
        if docker ps -a --format '{{.Names}}' | grep -q '^aladin-redis-prod$'; then
          echo "Container aladin-redis-prod already exists"
          
          # Check if it's running
          if docker ps --format '{{.Names}}' | grep -q '^aladin-redis-prod$'; then
            echo "✅ Redis is already running, reusing existing container"
          else
            echo "Starting stopped Redis container..."
            docker start aladin-redis-prod
            sleep 3
          fi
        else
          echo "Creating new Redis container with docker-compose..."
          docker-compose -f docker-compose.yml up -d redis
          sleep 5
        fi
        
        # Health check
        docker exec aladin-redis-prod redis-cli ping
        
        # Show running containers
        echo ""
        echo "=== Redis Status ==="
        docker ps --filter name=aladin-redis-prod
        docker inspect aladin-redis-prod --format='Status: {{.State.Status}} | Uptime: {{.State.StartedAt}}'
    
    - name: Install PM2 (if not installed)
      run: |
        if ! command -v pm2 &> /dev/null; then
          echo "Installing PM2..."
          npm install -g pm2
        else
          echo "PM2 already installed"
        fi
    
    - name: Deploy Application
      run: |
        # Stop old process (if exists)
        pm2 delete aladin-backend || true
        
        # Start new process
        pm2 start dist/server.js \
          --name aladin-backend \
          --instances max \
          --env production
        
        # Save PM2 process list
        pm2 save
        
        # Setup startup script (first time)
        pm2 startup systemd -u $(whoami) --hp $HOME || true
    
    - name: Show deployment status
      run: |
        echo "=== Deployment Status ==="
        pm2 status
        echo ""
        echo "=== Application Info ==="
        pm2 info aladin-backend
    
    - name: Health check
      run: |
        echo "Waiting for app to start..."
        sleep 5
        
        # Simple health check
        if pm2 list | grep -q "aladin-backend.*online"; then
          echo "✅ Application is running!"
        else
          echo "❌ Application failed to start!"
          pm2 logs aladin-backend --lines 50 --nostream
          exit 1
        fi

