# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD BACKEND-API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./back-end

    steps:
    - uses: actions/checkout@v4
    
    # Setup Python for mediasoup native modules
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './back-end/package-lock.json'
    
    # Install system dependencies for mediasoup (Linux only)
    - name: Install build dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-pip
    
    # Install system dependencies for mediasoup (Windows)
    - name: Install build dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install python -y
        choco install visualstudio2022buildtools -y
        choco install visualstudio2022-workload-vctools -y
      shell: powershell
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    # - name: Run tests
    #   run: npm test

